SEPARADOR = '</>'
FINAL_PRODUCTO = '<!>'
SEPARADOR_NOMBRE_IMAGEN = ':::'
SEPARADOR_FINAL_IMAGEN = '<<<'
SEPARADOR_2 = '///'
DIRECCION_SERVIDOR_CATALOGO = ('localhost', 10000)
DIRECCION_SERVIDOR_IMAGENES = ('localhost', 10001)
DIRECTORIO = 'servidor\\Imagenes\\'